---
- name: create subnet for lb2
  hosts: control
  vars_prompt:
    - name: "cidr_block_subnet8"
      prompt: "Enter the CIDR block you want for lb2 subnet"
      private: no
    - name: "subnet_name8"
      prompt: "Enter the name of the lb2 subnet"
      private: no
    - name: "subnet_az8"
      prompt: "Enter the availability zone of lb2 subnet"
      private: no

  tasks:
    - name: creating lb2
      set_fact:
        cidr_block_subnet: "{{cidr_block_subnet8}}"
        subnet_name: "{{subnet_name8}}"
        az: "{{subnet_az8}}"
  roles:
    - subnet
