---
- name: create VPC
  hosts: control
  gather_facts: flase
  vars_prompt:
    - name: "cidr_block"
      prompt: "Enter the CIDR block you want"
      private: no
    - name: "vpc_name"
      prompt: "Enter the name of the VPC"
      private: no
  tasks:
    - set_fact:
        cidr_block: "{{cidr_block}}"
        vpc_name: "{{vpc_name}}"
  roles:
    - vpc
