---
- name: create subnet for webserver2
  hosts: control
  vars_prompt:
    - name: "cidr_block_subnet2"
      prompt: "Enter the CIDR block you want for web server 1 subnet"
      private: no
    - name: "subnet_name2"
      prompt: "Enter the name of the web server 2 subnet"
      private: no
    - name: "subnet_az2"
      prompt: "Enter the availability zone of web server 2 subnet"
      private: no

  tasks:
    - name: creating webserver2
      set_fact:
        cidr_block_subnet: "{{cidr_block_subnet2}}"
        subnet_name: "{{subnet_name2}}"
        az: "{{subnet_az2}}"
  roles:
    - subnet
