---
# tasks file for subnet
# this can be use as common roles for each LAMP stack
- name: creating subnets "{{subnet_name}}"
    ec2_vpc_subnet:
      state: present
      vpc_id: "{{ vpc.vpc.id }}"
      region: "{{default_region}}"
      az: "{{subnet_az}}"
      cidr: "{{cidr_block}}"
      resource_tags:
        Name: "{{subnet_name}}"
register: output
# I want store each Subnet ID for Each stack
# I found combined jina function which replace variable value
# if so, what if I combined this output to a variable of stack
# then luanch instanes on specific subnets
- name: get subnetid of particular Stack
  set_fact:
    subnetid: ""{{ subnetid | combine({subnetinfo: output.subnets.id}) }}"

# subnetinfo is dynamic variable and it is passed with each stack subnet yml
# and I am overwriting output
