---
# tasks file for target_groups

- name: Creating target groups
  elb_target_group:
    name: applbgroup
    region: "{{default_region}}"
    protocol: http
    port: 80
    vpc_id: "{{ vpc.vpc.id }}"
    targets:
      - Id: "{{ info.webserver1.instance_ids[0]}}"
        Port: 80
      - Id: "{{ info.webserver2.instance_ids[0]}}"
        Port: 80
    state: present
