---
# tasks file for vpc

- name: Creating VPC
  ec2_vpc_net:
    name: "{{vpc_name}}"
    region: "{{default_region}}"
    state: present
    cidr_block: "{{cidr_block}}"
    tenancy: default
    dns_hostnames: yes
    dns_support: yes
  register: vpc
